/**
 * A box item stored in the cloud.
 */
export type RemoteBoxEntry = {
	/** Unique key of the item (generated by the client). */
	key: string;
	/** Serialized item (`PokemonBoxItem.serialize()`). */
	data: string;
};

/**
 * Cloud API to read and write the box of the signed-in user.
 */
export interface BoxApi {
	/**
	 * Get all items in the order they were first added.
	 */
	getBox(): Promise<RemoteBoxEntry[]>;

	/**
	 * Add or update items.
	 * New items should be appended to the end of the box.
	 */
	putBoxItems(entries: RemoteBoxEntry[]): Promise<void>;

	/**
	 * Delete items.
	 */
	deleteBoxItems(keys: string[]): Promise<void>;
}

const fakeStores = new Map<string, Map<string, string>>();

/**
 * In-memory BoxApi used until the Firebase Functions API is implemented.
 *
 * Data is kept per user only while the page is open.
 */
export class FakeBoxApi implements BoxApi {
	private readonly store: Map<string, string>;
	private readonly delay: number;

	/**
	 * Initialize FakeBoxApi.
	 * @param uid User ID.
	 * @param delay Simulated network delay in milliseconds.
	 */
	constructor(uid: string, delay = 500) {
		let store = fakeStores.get(uid);
		if (store === undefined) {
			store = new Map();
			fakeStores.set(uid, store);
		}
		this.store = store;
		this.delay = delay;
	}

	async getBox(): Promise<RemoteBoxEntry[]> {
		await this.wait();
		return Array.from(this.store, ([key, data]) => ({ key, data }));
	}

	async putBoxItems(entries: RemoteBoxEntry[]): Promise<void> {
		await this.wait();
		for (const entry of entries) {
			this.store.set(entry.key, entry.data);
		}
	}

	async deleteBoxItems(keys: string[]): Promise<void> {
		await this.wait();
		for (const key of keys) {
			this.store.delete(key);
		}
	}

	private wait(): Promise<void> {
		return new Promise((resolve) => setTimeout(resolve, this.delay));
	}
}
