/**
 * A box item stored in the cloud.
 */
export type RemoteBoxEntry = {
	/** Item ID (generated by the server). */
	id: string;
	/** Serialized item (`PokemonBoxItem.serialize()`). */
	data: string;
};

/**
 * Response of `BoxApi.getBoxItems`.
 */
export type RemoteBoxItems = {
	/** All items in the order they were added. */
	items: RemoteBoxEntry[];
	/** True if the box is empty and has never been initialized. */
	needsInit: boolean;
};

/**
 * Cloud API to read and write the box of the signed-in user.
 */
export interface BoxApi {
	/**
	 * Get all items in the order they were added.
	 */
	getBoxItems(): Promise<RemoteBoxItems>;

	/**
	 * Add items to the end of the box.
	 * @param data Serialized items.
	 * @returns IDs of the added items in the same order as `data`.
	 */
	addBoxItems(data: string[]): Promise<string[]>;

	/**
	 * Update existing items.
	 * Fails (and updates nothing) if any item does not exist.
	 */
	updateBoxItems(entries: RemoteBoxEntry[]): Promise<void>;

	/**
	 * Delete items. Unknown IDs are ignored.
	 */
	deleteBoxItems(ids: string[]): Promise<void>;
}

/**
 * In-memory BoxApi for tests.
 */
export class FakeBoxApi implements BoxApi {
	private readonly store = new Map<string, string>();
	private nextId = 0;
	private initialized = false;

	async getBoxItems(): Promise<RemoteBoxItems> {
		const items = Array.from(this.store, ([id, data]) => ({ id, data }));
		return { items, needsInit: items.length === 0 && !this.initialized };
	}

	async addBoxItems(data: string[]): Promise<string[]> {
		this.initialized = true;
		return data.map((x) => {
			const id = `id${this.nextId++}`;
			this.store.set(id, x);
			return id;
		});
	}

	async updateBoxItems(entries: RemoteBoxEntry[]): Promise<void> {
		if (entries.some((x) => !this.store.has(x.id))) {
			throw new Error("item not found");
		}
		for (const entry of entries) {
			this.store.set(entry.id, entry.data);
		}
	}

	async deleteBoxItems(ids: string[]): Promise<void> {
		for (const id of ids) {
			this.store.delete(id);
		}
	}
}
